In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = "*************/Uncleaned_DS_jobs.csv"
df = pd.read_csv(file_path)

In [ ]:
df.head()

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
df.columns

Index(['index', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors'],
      dtype='object')

In [ ]:
df.shape

(672, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 672 entries, 0 to 671
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              672 non-null    int64
 1   Job Title          672 non-null    object
 2   Salary Estimate    672 non-null    object
 3   Job Description    672 non-null    object
 4   Rating             672 non-null    float64
 5   Company Name       672 non-null    object
 6   Location           672 non-null    object
 7   Headquarters       672 non-null    object
 8   Size               672 non-null    object
 9   Founded            672 non-null    int64
 10  Type of ownership  672 non-null    object
 11  Industry           672 non-null    object
 12  Sector             672 non-null    object
 13  Revenue            672 non-null    object
 14  Competitors        672 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 78.9+ KB

In [ ]:
df.isnull().sum()

index                0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe(include='object')

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Type of ownership,Industry,Sector,Revenue,Competitors
count,672,672,672,672,672,672,672,672,672,672,672,672
unique,172,30,489,432,207,229,9,13,58,23,14,108
top,Data Scientist,$75K-$131K (Glassdoor est.),Job Overview: The Data Scientist is a key memb...,Hatch Data Inc,"San Francisco, CA","New York, NY",51 to 200 employees,Company - Private,-1,Information Technology,Unknown / Non-Applicable,-1
freq,337,32,12,12,69,33,135,397,71,188,213,501

Things i am going to do :
drop unwanted column

1.   make salary column int
2.   extract info out of job descripiton
3. remove int from company name
4. get a state column from value of location
5. create some features

In [ ]:
df.drop('index', inplace=True, axis=1)

In [ ]:
df['Salary Estimate'].head()

0    $137K-$171K (Glassdoor est.)
1    $137K-$171K (Glassdoor est.)
2    $137K-$171K (Glassdoor est.)
3    $137K-$171K (Glassdoor est.)
4    $137K-$171K (Glassdoor est.)
Name: Salary Estimate, dtype: object

In [ ]:
df['Salary Estimate'].unique()

array(['$137K-$171K (Glassdoor est.)', '$75K-$131K (Glassdoor est.)',
       '$79K-$131K (Glassdoor est.)', '$99K-$132K (Glassdoor est.)',
       '$90K-$109K (Glassdoor est.)', '$101K-$165K (Glassdoor est.)',
       '$56K-$97K (Glassdoor est.)', '$79K-$106K (Glassdoor est.)',
       '$71K-$123K (Glassdoor est.)', '$90K-$124K (Glassdoor est.)',
       '$91K-$150K (Glassdoor est.)', '$141K-$225K (Glassdoor est.)',
       '$145K-$225K(Employer est.)', '$79K-$147K (Glassdoor est.)',
       '$122K-$146K (Glassdoor est.)', '$112K-$116K (Glassdoor est.)',
       '$110K-$163K (Glassdoor est.)', '$124K-$198K (Glassdoor est.)',
       '$79K-$133K (Glassdoor est.)', '$69K-$116K (Glassdoor est.)',
       '$31K-$56K (Glassdoor est.)', '$95K-$119K (Glassdoor est.)',
       '$212K-$331K (Glassdoor est.)', '$66K-$112K (Glassdoor est.)',
       '$128K-$201K (Glassdoor est.)', '$138K-$158K (Glassdoor est.)',
       '$80K-$132K (Glassdoor est.)', '$87K-$141K (Glassdoor est.)',
       '$92K-$155K (Glassdoor est.)', '$105K-$167K (Glassdoor est.)'],
      dtype=object)

In [ ]:
df['Salary Estimate'].apply(lambda x: x.split('(')[0]).unique()

array(['$137K-$171K ', '$75K-$131K ', '$79K-$131K ', '$99K-$132K ',
       '$90K-$109K ', '$101K-$165K ', '$56K-$97K ', '$79K-$106K ',
       '$71K-$123K ', '$90K-$124K ', '$91K-$150K ', '$141K-$225K ',
       '$145K-$225K', '$79K-$147K ', '$122K-$146K ', '$112K-$116K ',
       '$110K-$163K ', '$124K-$198K ', '$79K-$133K ', '$69K-$116K ',
       '$31K-$56K ', '$95K-$119K ', '$212K-$331K ', '$66K-$112K ',
       '$128K-$201K ', '$138K-$158K ', '$80K-$132K ', '$87K-$141K ',
       '$92K-$155K ', '$105K-$167K '], dtype=object)

In [ ]:
df['Salary Estimate'].apply(lambda x: x.split('(')[0].strip())

0      $137K-$171K
1      $137K-$171K
2      $137K-$171K
3      $137K-$171K
4      $137K-$171K
          ...
667    $105K-$167K
668    $105K-$167K
669    $105K-$167K
670    $105K-$167K
671    $105K-$167K
Name: Salary Estimate, Length: 672, dtype: object

In [ ]:
df['Salary Estimate'].unique()

array(['$137K-$171K (Glassdoor est.)', '$75K-$131K (Glassdoor est.)',
       '$79K-$131K (Glassdoor est.)', '$99K-$132K (Glassdoor est.)',
       '$90K-$109K (Glassdoor est.)', '$101K-$165K (Glassdoor est.)',
       '$56K-$97K (Glassdoor est.)', '$79K-$106K (Glassdoor est.)',
       '$71K-$123K (Glassdoor est.)', '$90K-$124K (Glassdoor est.)',
       '$91K-$150K (Glassdoor est.)', '$141K-$225K (Glassdoor est.)',
       '$145K-$225K(Employer est.)', '$79K-$147K (Glassdoor est.)',
       '$122K-$146K (Glassdoor est.)', '$112K-$116K (Glassdoor est.)',
       '$110K-$163K (Glassdoor est.)', '$124K-$198K (Glassdoor est.)',
       '$79K-$133K (Glassdoor est.)', '$69K-$116K (Glassdoor est.)',
       '$31K-$56K (Glassdoor est.)', '$95K-$119K (Glassdoor est.)',
       '$212K-$331K (Glassdoor est.)', '$66K-$112K (Glassdoor est.)',
       '$128K-$201K (Glassdoor est.)', '$138K-$158K (Glassdoor est.)',
       '$80K-$132K (Glassdoor est.)', '$87K-$141K (Glassdoor est.)',
       '$92K-$155K (Glassdoor est.)', '$105K-$167K (Glassdoor est.)'],
      dtype=object)

In [ ]:
df['Salary Estimate'].head()

0    $137K-$171K (Glassdoor est.)
1    $137K-$171K (Glassdoor est.)
2    $137K-$171K (Glassdoor est.)
3    $137K-$171K (Glassdoor est.)
4    $137K-$171K (Glassdoor est.)
Name: Salary Estimate, dtype: object

In [ ]:
df['Salary Estimate'] = df['Salary Estimate'].apply(lambda x: x.replace('K','').replace('$',''))
df['Salary Estimate'] = df['Salary Estimate'].apply(lambda x: x.split('(')[0])

In [ ]:
df['Salary Estimate'].head()

0    137-171
1    137-171
2    137-171
3    137-171
4    137-171
Name: Salary Estimate, dtype: object

In [ ]:
df['min_salary'] = df['Salary Estimate'].apply(lambda x: int(x.split('-')[0]))
df['max_salary'] = df['Salary Estimate'].apply(lambda x: int(x.split('-')[1]))
df['avg_salary'] = (df['min_salary'] + df['max_salary']) / 2

In [ ]:
df[['min_salary', 'max_salary', 'avg_salary']].head(10)

   min_salary  max_salary  avg_salary
0         137         171       154.0
1         137         171       154.0
2         137         171       154.0
3         137         171       154.0
4         137         171       154.0
5         137         171       154.0
6         137         171       154.0
7         137         171       154.0
8         137         171       154.0
9         137         171       154.0

In [ ]:
df['Company Name']

0               Healthfirst\n3.1
1                   ManTech\n4.2
2            Analysis Group\n3.8
3                   INFICON\n3.5
4        Affinity Solutions\n2.9
                 ...
667                TRANZACT\n3.6
668                         JKGT
669                   AccessHope
670    ChaTeck Incorporated\n5.0
671           1-800-Flowers\n2.7
Name: Company Name, Length: 672, dtype: object

In [ ]:

df['Company Name'] = df['Company Name'].apply(lambda x: x.split('\n')[0])
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171,154.0
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171,154.0
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0

In [ ]:
df.Rating = np.where(df.Rating==-1.0,0,df.Rating)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171,154.0
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171,154.0
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0

In [ ]:
#
df['Location_split'] = df['Location'].str.split(',')

#
df['City'] = df['Location_split'].apply(lambda x: x[0].strip() if len(x) > 0 else None)
df['State'] = df['Location_split'].apply(lambda x: x[1].strip() if len(x) > 1 else None)

#
df.drop('Location_split', axis=1, inplace=True)
df.drop('Location', axis=1, inplace=True)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,City,State
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,"New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0,New York,NY
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,"Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171,154.0,Chantilly,VA
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,"Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171,154.0,Boston,MA
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,"Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0,Newton,MA
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0,New York,NY

In [ ]:
col_list = list(df.columns)
position = col_list.index('Company Name')
col_list.insert(position + 1, 'City')
col_list.insert(position + 2, 'State')
df = df[col_list]
df = df.loc[:, ~df.columns.duplicated()]

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,City,State,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,New York,NY,"New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,Chantilly,VA,"Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171,154.0
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,Boston,MA,"Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171,154.0
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,Newton,MA,"Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,NY,"New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0

In [ ]:


df['Headquarters_split'] = df['Headquarters'].str.split(',')
df['Headquarters_city'] = df['Headquarters_split'].apply(lambda x: x[0].strip() if len(x) > 0 else None)
df['Headquarters_state'] = df['Headquarters_split'].apply(lambda x: x[1].strip() if len(x) > 1 else None)

#
df.drop('Headquarters_split', axis=1, inplace=True)
df.drop('Headquarters', axis=1, inplace=True)

col_list = list(df.columns)
position = col_list.index('State')
col_list.insert(position + 1, 'Headquarters_city')
col_list.insert(position + 2, 'Headquarters_state')

df = df[col_list]
df = df.loc[:, ~df.columns.duplicated()]

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,City,State,Headquarters_city,Headquarters_state,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,New York,NY,New York,NY,1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,Chantilly,VA,Herndon,VA,5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137,171,154.0
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,Boston,MA,Boston,MA,1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137,171,154.0
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,Newton,MA,Bad Ragaz,Switzerland,501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,NY,New York,NY,51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0

In [ ]:
df.Founded

0      1993
1      1968
2      1981
3      2000
4      1998
       ...
667    1989
668      -1
669      -1
670      -1
671    1976
Name: Founded, Length: 672, dtype: int64

In [ ]:
df[df['Founded'] == -1][['Company Name', 'Founded']]

                 Company Name  Founded
69                     CareDx       -1
112        Maxar Technologies       -1
154  Covid-19 Search Partners       -1
158       Radical Convergence       -1
162        Maxar Technologies       -1
..                        ...      ...
662          SolutionIT, Inc.       -1
664       Clear Ridge Defense       -1
668                      JKGT       -1
669                AccessHope       -1
670      ChaTeck Incorporated       -1

[118 rows x 2 columns]

In [ ]:
df['Founded'] = df['Founded'].replace(-1, np.nan)
df['Founded'] = df['Founded'].astype('Int64')
df.Founded

0      1993
1      1968
2      1981
3      2000
4      1998
       ...
667    1989
668    <NA>
669    <NA>
670    <NA>
671    1976
Name: Founded, Length: 672, dtype: Int64

In [ ]:
df['Job Description'][1].split('\n')

['Secure our Nation, Ignite your Future',
 '',
 'Join the top Information Technology and Analytic professionals in the industry to make invaluable contributions to our national security on a daily basis. In this innovative, self-contained, Big Data environment, the ManTech team is responsible for everything from infrastructure, to application development, to data science, to advanced analytics and beyond. The team is diverse, the questions are thought-provoking, and the opportunities for growth and advancement are numerous',
 '',
 'The successful candidate will possess a diverse range of data-focused skills and experience, both technical and analytical. They will have a strong desire and capability for problem solving, data analysis and troubleshooting, analytical thinking, and experimentation.',
 '',
 'Duties, Tasks & Responsibilities',
 'Working with large, complex, and disparate data sets',
 'Designing and implementing innovative ways to analyze and exploit the Sponsors data holdings',
 'Researching and reporting on a wide variety of Sponsor inquiries',
 'Raising proactive inquiries to the Sponsor based on observations and proposed data analysis/exploitation',
 'Solving difficult, non-routine problems by applying advanced analytical methodologies, and improving analytic methodologies',
 'Developing custom searches',
 'Communicating and coordinating with internal and external partners as needed',
 'Required Experience, Skills, & Technologies',
 '',
 'Thorough knowledge of appropriate analytic tools and methodologies in one or more of the following:',
 'Applied mathematics (e.g. probability and statistics, formal modeling, computational social sciences)',
 'Computer programming (e.g. programming languages, math/statistics packages, computer science, machine learning, scientific computing)',
 'Ability to code or script in one or more general programming language',
 'Experience with and theoretical understanding of algorithms for classification, regression, clustering, and anomaly detection',
 'Knowledge of relational databases, including SQL and large-scale distributed systems (e.g. Hadoop)',
 'Expertise with statistical data analysis (e.g. linear models, multivariate analysis, stochastic models, sampling methods)',
 'Demonstrated effectiveness in collecting information and accurately representing/visualizing it to non-technical third parties',
 'TS/SCI with Polygraph',
 'Bachelor of Science or equivalent and 12-15 years related experience, but will consider all levels of experience.',
 'Desired Experience, Skills & Technologies',
 'Previous investigative experience using a combination of technical and analytic skills',
 '#LI-DU1',
 '',
 'ManTech International Corporation, as well as its subsidiaries proactively fulfills its role as an equal opportunity employer. We do not discriminate against any employee or applicant for employment because of race, color, sex, religion, age, sexual orientation, gender identity and expression, national origin, marital status, physical or mental disability, status as a Disabled Veteran, Recently Separated Veteran, Active Duty Wartime or Campaign Badge Veteran, Armed Forces Services Medal, or any other characteristic protected by law.',
 '',
 "If you require a reasonable accommodation to apply for a position with ManTech through its online applicant system, please contact ManTech's Corporate EEO Department at (703) 218-6000. ManTech is an affirmative action/equal opportunity employer - minorities, females, disabled and protected veterans are urged to apply. ManTech's utilization of any external recruitment or job placement agency is predicated upon its full compliance with our equal opportunity/affirmative action policies. ManTech does not accept resumes from unsolicited recruiting firms. We pay no fees for unsolicited services.",
 '',
 'If you are a qualified individual with a disability or a disabled veteran, you have the right to request an accommodation if you are unable or limited in your ability to use or access http://www.mantech.com/careers/Pages/careers.aspx as a result of your disability. To request an accommodation please click careers@mantech.com and provide your name and contact information.']

In [ ]:
df['python'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
df['excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df['hadoop'] = df['Job Description'].apply(lambda x: 1 if 'hadoop' in x.lower() else 0)
df['spark'] = df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df['aws'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
df['tableau'] = df['Job Description'].apply(lambda x: 1 if 'tableau' in x.lower() else 0)
df['big_data'] = df['Job Description'].apply(lambda x: 1 if 'big data' in x.lower() else 0)
df['R'] = df['Job Description'].apply(lambda x: 1 if 'big data' in x.lower() else 0)
df['Tensorflow'] = df['Job Description'].apply(lambda x: 1 if 'big data' in x.lower() else 0)
df['powerbi'] = df['Job Description'].apply(lambda x: 1 if 'big data' in x.lower() else 0)
df['PyTorch'] = df['Job Description'].apply(lambda x: 1 if 'big data' in x.lower() else 0)

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,City,State,Headquarters_city,Headquarters_state,Size,...,excel,hadoop,spark,aws,tableau,big_data,R,Tensorflow,powerbi,PyTorch
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,New York,NY,New York,NY,1001 to 5000 employees,...,0,0,0,1,0,0,0,0,0,0
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,Chantilly,VA,Herndon,VA,5001 to 10000 employees,...,0,1,0,0,0,1,1,1,1,1
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,Boston,MA,Boston,MA,1001 to 5000 employees,...,1,0,0,1,0,0,0,0,0,0
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,Newton,MA,Bad Ragaz,Switzerland,501 to 1000 employees,...,1,0,0,1,0,0,0,0,0,0
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,NY,New York,NY,51 to 200 employees,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
df['Job Title'].value_counts()

Job Title
Data Scientist                                                      337
Data Engineer                                                        26
Senior Data Scientist                                                19
Machine Learning Engineer                                            16
Data Analyst                                                         12
                                                                   ...
Sr. Research Associate/ Scientist, NGS prep & Molecular Genomics      1
Developer III - Data Science                                          1
Hydrogen/Tritium Materials Scientist (Experienced)                    1
Data Scientist/Data Analytics Practitioner                            1
AI/ML - Machine Learning Scientist, Siri Understanding                1
Name: count, Length: 172, dtype: int64

In [ ]:
def title_simplifier(title):
    if 'data scientist' in title.lower():
        return 'data scientist'
    elif 'data engineer' in title.lower():
        return 'data engineer'
    elif 'analyst' in title.lower():
        return 'analyst'
    elif 'machine learning' in title.lower():
        return 'mle'
    elif 'manager' in title.lower():
        return 'manager'
    elif 'director' in title.lower():
        return 'director'
    else:
        return 'na'

def seniority(title):
    if 'sr' in title.lower() or 'senior' in title.lower() or 'sr' in title.lower() or 'lead' in title.lower() or 'principal' in title.lower():
            return 'senior'
    elif 'jr' in title.lower() or 'jr.' in title.lower():
        return 'jr'
    else:
        return 'na'

In [ ]:
df['job_simplification'] = df['Job Title'].apply(title_simplifier)

df.job_simplification.value_counts()

job_simplification
data scientist    455
na                 69
analyst            55
data engineer      47
mle                36
manager             7
director            3
Name: count, dtype: int64

In [ ]:
df['Seniority'] = df['Job Title'].apply(seniority)
df.seniority.value_counts()

seniority
na        576
senior     94
jr          2
Name: count, dtype: int64

In [ ]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,City,State,Headquarters_city,Headquarters_state,Size,...,aws,tableau,big_data,R,Tensorflow,powerbi,PyTorch,seniority,job_simplification,Seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,New York,NY,New York,NY,1001 to 5000 employees,...,1,0,0,0,0,0,0,senior,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,Chantilly,VA,Herndon,VA,5001 to 10000 employees,...,0,0,1,1,1,1,1,na,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,Boston,MA,Boston,MA,1001 to 5000 employees,...,1,0,0,0,0,0,0,na,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,Newton,MA,Bad Ragaz,Switzerland,501 to 1000 employees,...,1,0,0,0,0,0,0,na,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,NY,New York,NY,51 to 200 employees,...,0,0,0,0,0,0,0,na,data scientist,na

In [ ]:
df.drop('seniority', axis=1, inplace=True)

In [ ]:
df['Competitors'] = df['Competitors'].replace("-1", np.nan)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_rows', None)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,City,State,Headquarters_city,Headquarters_state,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,python,excel,hadoop,spark,aws,tableau,big_data,R,Tensorflow,powerbi,PyTorch,job_simplification,Seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,New York,NY,New York,NY,1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0,0,0,0,0,1,0,0,0,0,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,Chantilly,VA,Herndon,VA,5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),NaN,137,171,154.0,0,0,1,0,0,0,1,1,1,1,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,Boston,MA,Boston,MA,1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),NaN,137,171,154.0,1,1,0,0,1,0,0,0,0,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,Newton,MA,Bad Ragaz,Switzerland,501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0,1,1,0,0,1,0,0,0,0,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,NY,New York,NY,51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0,1,1,0,0,0,0,0,0,0,0,0,data scientist,na

In [ ]:
df["Type of ownership"].value_counts(dropna=False)

Type of ownership
Company - Private                 397
Company - Public                  153
Nonprofit Organization             36
Subsidiary or Business Segment     28
-1                                 27
Government                         10
Other Organization                  5
Private Practice / Firm             4
Unknown                             4
College / University                3
Self-employed                       2
Contract                            2
Hospital                            1
Name: count, dtype: int64

In [ ]:
df["Type of ownership"] = df["Type of ownership"].replace({
    "-1": "Unknown ",
    "Company - Private": "Private Company",
    "Company - Public": "Public Company",
    "Subsidiary or Business Segment": "Subsidiary",
    "Private Practice / Firm": "Private Firm",
    "College / University": "University",
    "Self-employed": "Freelancer",
    "Contract": "Contract-based",
    "Hospital": "Healthcare Institution", "Self-employed": "Freelancer "

})

In [ ]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,City,State,Headquarters_city,Headquarters_state,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,python,excel,hadoop,spark,aws,tableau,big_data,R,Tensorflow,powerbi,PyTorch,job_simplification,Seniority
0,Sr Data Scientist,137-171,Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst,New York,NY,New York,NY,1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137,171,154.0,0,0,0,0,1,0,0,0,0,0,0,data scientist,senior
1,Data Scientist,137-171,"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech,Chantilly,VA,Herndon,VA,5001 to 10000 employees,1968,Public Company,Research & Development,Business Services,$1 to $2 billion (USD),NaN,137,171,154.0,0,0,1,0,0,0,1,1,1,1,1,data scientist,na
2,Data Scientist,137-171,Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group,Boston,MA,Boston,MA,1001 to 5000 employees,1981,Private Firm,Consulting,Business Services,$100 to $500 million (USD),NaN,137,171,154.0,1,1,0,0,1,0,0,0,0,0,0,data scientist,na
3,Data Scientist,137-171,JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON,Newton,MA,Bad Ragaz,Switzerland,501 to 1000 employees,2000,Public Company,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137,171,154.0,1,1,0,0,1,0,0,0,0,0,0,data scientist,na
4,Data Scientist,137-171,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,New York,NY,New York,NY,51 to 200 employees,1998,Private Company,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137,171,154.0,1,1,0,0,0,0,0,0,0,0,0,data scientist,na

In [ ]:
df.to_csv('Cleaned_Df_Joboffers.csv', index=False)